### ISSUE TITLE
doc generate

### ISSUE THREAD

**Issue by wanghaisheng** [apidoc/apidoc-spec#1]
how can i generate doc like http://apidocjs.com/example/#api- from the file under directory https://github.com/apidoc/apidoc-spec/tree/master/examples/v0.1

**Comment by rottmann** [comment]
You find the updated example here: https://github.com/apidoc/apidoc-example/tree/master/v0.2.0/src

**Comment by ghost** [comment]
@wanghaisheng was @rottmann able to answer your question?
