### ISSUE TITLE
Suggestion for versioning

### ISSUE THREAD

**Issue by alexkubica** [apidoc/apidoc-spec#3]
I hope it is the correct place to ask
So I have a suggestion to make versioning easier:
What if you add a command to copy all current apiDoc blocks to a file the will keep all history and then you update all those block to a newer version (as the one mentioned in apidoc.json)?
You could also add an apiDoc parameter named `@apiOriginal` to mark blocks as the updated ones, all unoriginal blocks won't be copied to the history file.
The specs might need improvement but if it sounds good I'm willing to try and make a PR with this feature.

**Comment by rottmann** [comment]
A separate grunt task would be good for solution for this usecase.

The grunt task could use [apidoc-core](https://github.com/apidoc/apidoc-core) to retrieve the current project.json data, this data can be easy merged into a history.json file.
Then the task can generate a doc from all with apidoc.

**Comment by alexkubica** [comment]
What if you don't use a grunt? Also, could the task update the apidocs? Such as changing versions?

**Comment by rottmann** [comment]
grunt-task (or gulp) are js programs, you can do what ever you want with a task.

It don't have to be a grunt task, you can create an independent program (a grunt task could then use your program).

For examples view the [build tools](https://github.com/apidoc/apidoc#build-tools) or the [converter](https://github.com/apidoc/apidoc#converter). Some converter use apidoc-core to get the json data.

**Comment by alexkubica** [comment]
Okay thanks, i'll try creating a task.
